### ISSUE TITLE
[request] give options to override the colours for the inner and outer unset

### ISSUE THREAD

**Issue by markusdf** [Larkinabout/fvtt-challenge-tracker#10]
Currently we can set only one colour for inner, and one for outer. It would be ideal if we could set 2 colours for inner, and 2 for outer. e.g. for a danger indicator
![Untitled](https://user-images.githubusercontent.com/5422580/179992872-86ec5bf7-dc3b-4674-aa10-3d5f6e4b23f7.png)
, it would switch from green to red, instead of transparent red to red.

**Comment by Larkinabout** [comment]
Added in release 0.8.
