### ISSUE TITLE
[Bug] Error: User Player1 lacks permission to update User [2eCcEi9HdTwCxqFx]

### ISSUE THREAD

**Issue by jessev14** [Larkinabout/fvtt-challenge-tracker#11]
When a GM user opens a "Show to Others" tracker, player users get the above error message.

I believe the cause is in `ChallengeTrackerForm.set`. It tries to set a flag on the tracker's owner, but only GM users have permission to do so. My guess is there's a `isGM` user check missing somewhere before this method is called.

**Comment by Larkinabout** [comment]
Ah, yeah, it's also breaking the link to the owner, so their flags are going to get messed up. I'll fix it for the next release and add something to tidy up orphaned flags. Thanks!

**Comment by Larkinabout** [comment]
Fixed in release 0.8.
