### ISSUE TITLE
Provide public macro functions for tracker values

### ISSUE THREAD

**Issue by megahead11** [Larkinabout/fvtt-challenge-tracker#13]
I'm not certain if they're buried in and not documented, or are private, but I think it could be nice to have functions for macros to refer to the values of a given tracker.
It could be nice to refer to the tracker's values or allow macros to change them. It might seem a bit redundant when you can simply click the tracker, but having macros manipulate it or read it can be handy, especially in high automation games. 

Could probably go alongside the open/close hooks.

**Comment by Larkinabout** [comment]
Added in release 0.9.
