### ISSUE TITLE
Button Disable

### ISSUE THREAD

**Issue by brunocalado** [Larkinabout/fvtt-challenge-tracker#16]
Hi.

Can add some options for the button?
![image](https://user-images.githubusercontent.com/4999783/180886615-e0e55fa3-b7d5-4094-b69e-f7cb754824ae.png)

- [ ] Disable it for everyone
- [ ] Disable it for player
- [ ] Show the button in the left sidebar instead the player name

This prevent some conflict with modules and system; 

Related to:
https://github.com/Larkinabout/fvtt-challenge-tracker/issues/15

**Comment by Larkinabout** [comment]
I assume those are SWADE's bennies? I saw those mentioned in the minimal UI code. At least the Challenge Tracker button looks quite nice alongside them; aside from the odd alignment!

I'll add those suggested options, but I'll also look at how the button sits in the Player List, so groups can still have the option of keeping it on there without it looking weird alongside other buttons.

Where's the best place to stick it on the left-side bar?

**Comment by brunocalado** [comment]
> I assume those are SWADE's bennies? I saw those mentioned in the minimal UI code. At least the Challenge Tracker button looks quite nice alongside them; aside from the odd alignment!
> 
> I'll add those suggested options, but I'll also look at how the button sits in the Player List, so groups can still have the option of keeping it on there without it looking weird alongside other buttons.
> 
> Where's the best place to stick it on the left-side bar?

I would guess the journal layer...
![image](https://user-images.githubusercontent.com/4999783/181009057-90946656-fb27-4b69-a8a7-42d1382bf5c5.png)

**Comment by Larkinabout** [comment]
Added in release 0.9.
