### ISSUE TITLE
Macros don't work anymore

### ISSUE THREAD

**Issue by brunocalado** [Larkinabout/fvtt-challenge-tracker#23]
I can't create the clock with macros anymore. I even tried the example in your readme.

Can you help?

Tks

![image](https://user-images.githubusercontent.com/4999783/189379537-c7dabe0e-755e-4e29-94c3-909becfaeac6.png)

**Comment by Larkinabout** [comment]
What Foundry VTT version and Challenge Tracker version are you running?

**Comment by brunocalado** [comment]
> What Foundry VTT version and Challenge Tracker version are you running?

![image](https://user-images.githubusercontent.com/4999783/189406226-cfc52204-8b0b-439b-9df1-ec976be17ccc.png)

**Comment by Larkinabout** [comment]
Just tested on those versions and mine still works. Do you have the Color Picker module enabled?

Can you also click on the `main.js:313:13` link and take a screenshot of where it highlights please.

I don't know why they might impact it, but maybe also try disabling other modules temporarily and see if it works then.

**Comment by brunocalado** [comment]
> Just tested on those versions and mine still works. Do you have the Color Picker module enabled?
> 
> Can you also click on the `main.js:313:14` link and take a screenshot of where it highlights please.
> 
> I don't know why they might impact it, but maybe also try disabling other modules temporarily and see if it works then.
 Color Picker was disabled

tks
