### ISSUE TITLE
Change the Scroll Default

### ISSUE THREAD

**Issue by brunocalado** [Larkinabout/fvtt-challenge-tracker#30]
Hi.

The option Scroll is really annoying you need to move around the scene and it's common to scroll over the tracker.

After I found out about this option I turn it off. But, it turn on by again. I don't know if change the browser or update the module looses this option.

But, anyway can you make the default for this Off? 

![image](https://user-images.githubusercontent.com/4999783/195932738-39e23fed-4dd0-4e7a-b4c3-8450920d0234.png)

**Comment by Larkinabout** [comment]
In this instance, I'd prefer to leave features enabled from the outset, for new users especially, but provide users with settings to disable the ones they don't like.

The latest version made some additions to the scroll functionality, though I'm not aware of why those would have impacted your stored module setting. I have, however, seen another case where updating Foundry VTT caused settings to reset to their defaults. If you have recently updated, that may be the culprit.

In either case, I would hope your choice sticks around in the future. I have also added the scroll option to the `ChallengeTracker.open()` and the Edit Challenge Tracker form, which will always override the module setting.
