### ISSUE TITLE
Forge version

### ISSUE THREAD

**Issue by RealityBlights** [Larkinabout/fvtt-challenge-tracker#31]
I'm curious to know if a v10 compatible iteration of this module will reach the Forge anytime soon.
(https://forge-vtt.com/)

**Comment by Larkinabout** [comment]
It looks like it's available here: https://forge-vtt.com/bazaar/package/challenge-tracker

2.2 is the latest v10 release and that is listed for me on that page. I just used the search on the Modules page to find it.
