### ISSUE TITLE
v11

### ISSUE THREAD

**Issue by brunocalado** [Larkinabout/fvtt-challenge-tracker#33]
Hi.

Can you update to v11?
![image](https://github.com/Larkinabout/fvtt-challenge-tracker/assets/4999783/210fec15-9d9e-486c-aaf0-fc40e71d1161)

tks

**Comment by Larkinabout** [comment]
In the works, just giving it a bit of a refactoring first.

**Comment by Larkinabout** [comment]
Added in Challenge Tracker 2.3.
