### ISSUE TITLE
Translation string missing in players list

### ISSUE THREAD

**Issue by kristianserrano** [Larkinabout/fvtt-challenge-tracker#34]
The translation string for the tracker in the players list is missing.

![Screenshot 2023-06-03 at 12 26 32 PM](https://github.com/Larkinabout/fvtt-challenge-tracker/assets/1796189/7234fd4b-6780-4195-bf46-48b58107b23c)

**Comment by Larkinabout** [comment]
Fixed in Challenge Tracker 2.3.
