### ISSUE TITLE
Function to execute and/or hook on closing the tracker.

### ISSUE THREAD

**Issue by SalieriC** [Larkinabout/fvtt-challenge-tracker#5]
It would be really great to have a hook called when the tracker is closed, possibly even a way to execute a function that is executed when it is closed, provided when it is created. That would allow users to set up flags for opening the tracker with the same current when they left the tracker. That'd open up a lot of opportunities.

**Comment by Larkinabout** [comment]
I'll look into this alongside development on persisting Challenge Tracker across sessions.

**Comment by Larkinabout** [comment]
Added in release 0.9.
